### ISSUE TITLE
Image uploading doesn't seem to work

### ISSUE THREAD

**Issue by falcon-git** [h5p/h5p-collage#10]
It takes quite some time before the image icon starts spinning. Perhaps nothing happens while uploading and then it starts spinning while downloading?

I thought the upload had failed until it started spinning.

**Comment by icc** [comment]
How can I reproduce this? What browser are you using, and are you using some kind of emulation or extension? 

When I test on h5p.org, the spinning starts right after I've selected the file and continues until the uploaded file is downloaded again.

**Comment by falcon-git** [comment]
Strange. Works perfectly here as well. I used chrome on H5P.org when I produced the problem and the same now when it worked perfectly
