### ISSUE TITLE
Uploading multiple images doesn't work

### ISSUE THREAD

**Issue by falcon-git** [h5p/h5p-collage#11]
I naturally pressed the next image before the first one was finished and selected an upload for that one as well. None of the images were uploaded.

**Comment by icc** [comment]
How can I reproduce this? Seems to work very well on h5p.org.

Although the overall uploading takes longer time when uploading multiple files.

**Comment by falcon-git** [comment]
Strange. Works perfectly here as well. I used chrome on H5P.org when I produced the problem and the same now when it worked perfectly
