### ISSUE TITLE
Spinner good or bad?

### ISSUE THREAD

**Issue by falcon-git** [h5p/h5p-collage#12]
I would think that showing the images as they are loaded the normal way would be much better than showing the spinner. The spinner is distracting, doesn't show the progress and give you no idea about what's to come. Is there a technical reason for using a throbber or is it there to make it look cool?

**Comment by icc** [comment]
I guess the current throbber is a little bit over the top.

Many applications use throbbers to indicate that something is loading. This is good UX. If an image have progressive loading the user doesn't know when the image is finished loading, i.e. if the quality will get any better, or if you're just sitting there and waiting for nothing.

Perhaps displaying a smaller throbber on top of the image while it's loading would be a better solution?

**Comment by falcon-git** [comment]
The last paragrapsh sounds like the best of both worlds. The throbber is cool, but I prefer progressive loading. I get to see some of it much sooner.

**Comment by mvmagnussen** [comment]
I agree that we should use a more subtle throbber. Something like this: http://codepen.io/anon/pen/WvpaNy

Not sure about the progressive loading, but would be nice to see it in action or external examples.

**Comment by icc** [comment]
Fixed so that there's only a throbber when uploading new images. Image loading is handled by the browser. (i.e. progressively if supported)
