### ISSUE TITLE
Didn't get the aspect ratio hand thing

### ISSUE THREAD

**Issue by falcon-git** [h5p/h5p-collage#13]
By default I could use the hand cursor to move the image a couple of pixels each way. When adjusting the aspect ratio all the picture frames became a lot taller. That was unexpected. What is the idea there?

**Comment by falcon-git** [comment]
(It might be that it should be called height instead of aspect ratio, and also that I'm missing a zoom per image feature)

**Comment by icc** [comment]
The idea is to adjust the height of the collage, which is relative to the width. Perhaps changing the aspect ratio formatting would help this, or changing the label. Put that give us the issue that there's really no unit of measurement for the height. 

I suggest changing formatting to *1:0.75*

**Comment by icc** [comment]
You can zoom per tile, just hold *z* while scrolling, or use +/- on your keyboard.

**Comment by falcon-git** [comment]
This is your content type so it is up to you, but I believe all your users will understand and predict what height does if you use the term. Changing formatting will probably also work.

I see the +/- description now, but I didn't see it initially and probably wouldn't have seen it either. Perhaps we could make this more clear somehow?

**Comment by icc** [comment]
I'll do some adjustments, trying to make it easier to use. I'm guessing our designer will have some feedback when he comes back as well.

**Comment by mvmagnussen** [comment]
In the initial design spec, there were buttons for zoom in/out on each image. There was also a more wysywig approach to editing the aspect ratio, by pulling the lower edge of the collage frame to adjust height. 
![00-collage-editor](https://cloud.githubusercontent.com/assets/1208362/8253466/8e8fa5a4-1690-11e5-93ee-5a982f1fa01c.jpg)

**Comment by icc** [comment]
Zoom buttons have been added. The *Pull to adjust height* didn't really work good when I tested it. There were some difficulties when we met the edge of the page, and some issues because the editor is in an iframe. I've renamed the height operator and put it at the bottom of the page. It should be easier to understand and use now. Perhaps we can look into the *Pull to adjust height* in a future version.
