### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by mvmagnussen** [h5p/h5p-collage#17]
Use only icons for image buttons (e.g. 'change image'), as suggested in the design spec. Add the tooltip functionality to describe what the button does, when this becomes available in H5P.

![00-collage-editor](https://cloud.githubusercontent.com/assets/1208362/8253745/e663b7fa-1692-11e5-9c58-ff1b9bbb5348.jpg)

**Comment by icc** [comment]
This has been implemented.
