### ISSUE TITLE
Add Ability to Hyperlink Images to other URLs

### ISSUE THREAD

**Issue by mrjarbenne** [h5p/h5p-collage#29]
A collage can be a great means of displaying access to different content in a course. Allowing the images in a collage to be hyperlinked would allow collage to be utilized to create navigation panels, or to link to larger versions of the image, etc., making in more useful in course design.

**Comment by timothyylim** [comment]
This is a great idea @mrjarbenne. If you could post in the feature request forum:

https://h5p.org/forum/16

That would be great. H5P.org will have voting on feature requests enabled in the near future and hopefully other members of the community will vote for it.
