### ISSUE TITLE
Hide advanced settings in editor

### ISSUE THREAD

**Issue by falcon-git** [h5p/h5p-collage#8]
Tile spacing, Frame and ascpect ratio in a collapsed fieldset?

**Comment by icc** [comment]
It would be great to group the settings, and perhaps put them beside each other to make use of all the horizontal space. I don't know about hiding them when the form isn't that big, and I wouldn't classify these settings as advanced.

**Comment by falcon-git** [comment]
Yeah, that could probably work, but then we probably also should do something with the titles. I didn't understand any of them. "0.5 tilespacing" is that em? Maybe not useful until after the images have been uploaded?

And is the frame around the images or around the entire thing? Is it the H5P frame with the copyright button and stuff?

I've already mentioned the aspect ratio. Probably would make more sense to call it height even if I understand why it is called aspect ratio after using it.

**Comment by icc** [comment]
What is wrong with *Tile Spacing*? If you try to google *tile spacing* it seems pretty clear what it is. Would you rather prefer that we called it clips, i.e. Clip Layout, Clip Spacing, or Clip Gutter?
The measurement itself is relative to the text size on the page. Don't know if putting in the *em* would help bloggers much, perhaps?

Would it be more understandable if we put the settings after the preview?

The *Frame* is the border surrounding the collage. Perhaps we should call it *Collage Frame*, even though we are in the *Collage* context, i.e. options that are not in the current context are prefixed with their context, e.g. *Tile*. The *Collage Preview* title should be updated to reflect this.

Perhaps we should do like image editors and display ratio in the format *1:0.75*?

**Comment by falcon-git** [comment]
1. The way it is set up you ask the user to first choose the layout, then the tile spacing. The wording isn't the biggest problem although picture spacing or something probably would be much better, but how can a user choose a tile spacing at this stage when it doesn't even have a unit?

2. After trying this out I think you should use something different. It doesn't seem to be a frame or border, it seems to be whitespace. Maybe "Collage spacing" or "Outer margin" or something?

3. I think height will work perfectly

**Comment by icc** [comment]
1. I believe Magnus chose the wording because it was the correct technical term to use after having worked with other tools. So you agree that we should put it after the preview?
2. I suggest we change the color of the tile spacing and frame when the frame is present, and remove it when it isn't.
3. Ok

**Comment by falcon-git** [comment]
1. Yes, or make it pop up after images are uploaded or something like that. (1) choose layout (2) upload images and position/zoom them (3) adjust (4) publish seems to be a natural workflow?

2.Worth a try!

**Comment by mvmagnussen** [comment]
FYI: The original wording was 'Inner frames' and 'Outer frame'.

**Comment by icc** [comment]
The wording has been changed to be simpler and easier to understand. The layout has always been re-ordered as suggested. It looks much better, but maybe not perfect. I'm closing this issue since there's been a lot of changes here. Magnus may create a separate issues if he feels that the UX or layout needs further adjusting.
